### ISSUE TITLE
单个Repo的Doc数量最多只能获取到100, 超出部分无法获取

### ISSUE THREAD

**Issue by ShingenYan** [M1r0ku/YuqueExport#6]
一个Repo, 最多只能获取100个Doc, 超出的无法获取

**Comment by M1r0ku** [comment]
这个我看了一下，是因为上周语雀官方那边的接口改了，每页最大返回100篇，链接：https://www.yuque.com/yuque/developer/openapi

![Yueque-Dev](https://github.com/M1r0ku/YuqueExport/assets/32028515/c968da1b-3fd9-4017-a4cb-e95da820a1ec)

**Comment by M1r0ku** [comment]
> 这个请问有解决办法吗

一个比较简单的方法是建一个新的知识库，每次选中100篇笔记复制过去，然后再下载该库的全部笔记就好了

**Comment by guanfenglinux** [comment]
class MyYuque(Yuque):
    def __init__(self, token=None, api_base=None):
        super().__init__(token=token)

    def repo_list_docs(self, namespace_or_id):
        offset = 0
        data_all = []
        while True:
            params = {
                "offset": offset,
                "limit": 100
            }
            result = self.send_request('GET', '/repos/%s/docs' % namespace_or_id.strip('/'), params=params)
            data = result["data"]
            data_all.extend(data)
            if len(data) < 100:
                break
            else:
                offset += 100
        return data_all

把这个重写了下

**Comment by M1r0ku** [comment]
> 这个请问有解决办法吗

已解决，请下载最新脚本代码
